from .Dynamic import Dynamic
class Particles(Dynamic):
    ClassName = "Particles"
    Properties = {
        "Playing": "boolean",
        "SpeedScale": "float",
        "Image": "resourceref",
        "TextureFilter": "int",
        "Color": "colorseries",
        "Lifetime": "numberrange",
        "Amount": "int",
        "Explosiveness": "float",
        "Gravity": "vector3",
        "VelocityDirection": "vector3",
        "InitialVelocity": "numberrange",
        "StartRotation": "numberrange",
        "AngularVelocity": "numberrange",
        "AngularVelocityOverLifetime": "numberseries",
        "LinearAcceleration": "numberrange",
        "LinearAccelerationOverLifetime": "numberseries",
        "RadialAcceleration": "numberrange",
        "RadialAccelerationOverLifetime": "numberseries",
        "TangentialAcceleration": "numberrange",
        "TangentialAccelerationOverLifetime": "numberseries",
        "OrbitalVelocity": "numberrange",
        "OrbitalVelocityOverLifetime": "numberseries",
        "Damping": "numberrange",
        "DampingOverLifetime": "numberseries",
        "ScaleOverVelocity": "numberrange",
        "ScaleOverVelocityCurve": "numberseries",
        "TurbulenceEnabled": "boolean",
        "TurbulenceInfluence": "numberrange",
        "TurbulenceOverLifetime": "numberseries",
        "TurbulenceNoiseScale": "float",
        "TurbulenceNoiseStrength": "float",
        "TurbulenceNoiseSpeed": "vector3",
        "Spread": "float",
        "Flatness": "float",
        "Scale": "numberrange",
        "ScaleOverLifetime": "numberseries",
        "HueVariation": "numberrange",
        "BlendMode": "int",
        "Shaded": "boolean",
        "EmissionShape": "int",
        "EmissionShapeScale": "vector3",
        "SimulationSpace": "int",
        "Orientation": "int",
    }
    def __init__(self):
        super().__init__()
        self.addProperties(Particles.Properties)